# Generated by Django 3.2.9 on 2021-12-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_post', models.TextField(max_length=200, verbose_name='Blog post')),
                ('publisher_name', models.CharField(max_length=200, verbose_name='Publisher name')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
