# Generated by Django 3.2.9 on 2021-12-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_subject',
            field=models.CharField(default='Subject', max_length=100, verbose_name='Blog subject'),
            preserve_default=False,
        ),
    ]
